server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <your-client-id>
            client-secret: <your-client-secret>
            scope: profile,email,openid
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs


  main:
    allow-circular-references: true

  data:
    redis:
      host: 192.168.1.234
      port: 6379
      database: 0
      password: zxs123123
      lettuce:
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: 10000ms

  #config for spring mvc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
